apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  - name: ClickHouse
    type: grafana-clickhouse-datasource
    url: http://clickhouse:8123
    editable: false
    jsonData:
      defaultDatabase: trading_events
      port: 9000