"""Built-in strategies and agent simulators for backtesting.

Strategies:
- BaseStrategy: Abstract base class for all backtest strategies
- MACDCrossover: Moving Average Convergence Divergence crossover
- SignalDrivenStrategy: Generic signal-based strategy

Agents (for EPIC-04 multi-agent simulation):
- SimulatedAgent: Base agent that produces signals
- RandomAgent: Random signal generator
- HeuristicAgent: Simple rule-based agent
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any

import numpy as np

from .core import Candle

# ─── Strategy Protocol ──────────────────────────────────────────────────────


class SignalAction(Enum):
    """Action generated by a strategy."""

    BUY = "buy"
    SELL = "sell"
    HOLD = "hold"
    CLOSE = "close"
    NO_TRADE = "no_trade"


@dataclass
class StrategySignal:
    """A signal generated by a strategy."""

    action: SignalAction
    symbol: str
    confidence: float = 0.0  # 0.0 to 1.0
    reason: str = ""
    stop_loss: float | None = None
    take_profit: float | None = None
    position_size: float = 0.0  # Fraction of portfolio (0.0 to 1.0)
    timestamp: datetime | None = None
    metadata: dict[str, Any] = field(default_factory=dict)


class BaseStrategy(ABC):
    """Base class for all backtest strategies.

    Subclass and implement `on_bar` to create a custom strategy.
    """

    def __init__(self, name: str = "custom") -> None:
        self.name = name
        self._history: list[Candle] = []
        # Von allen konkreten Strategien überschrieben (Ensemble/Regel/Prompt)
        self.instrument: str = ""
        self.initial_capital: float = 0.0
        self.candle_limit: int = 0

    def to_dict(self) -> dict[str, Any]:
        """Serialisiert die Strategie-Instanz für Reports (Subklassen erweitern)."""
        return {"name": self.name}

    @property
    def history(self) -> list[Candle]:
        return self._history

    @abstractmethod
    def on_bar(self, candle: Candle) -> StrategySignal | None:
        """Called with each new candle. Return a StrategySignal or None."""
        raise NotImplementedError

    def on_bars(self, candles: list[Candle]) -> list[StrategySignal]:
        """Process a batch of candles."""
        signals: list[StrategySignal] = []
        for c in candles:
            self._history.append(c)
            signal = self.on_bar(c)
            if signal is not None:
                signals.append(signal)
        return signals


# ─── MACD Crossover Strategy ────────────────────────────────────────────────


class MACDCrossover(BaseStrategy):
    """MACD (12, 26, 9) crossover strategy.

    BUY signal: MACD line crosses above signal line.
    SELL signal: MACD line crosses below signal line.

    Uses pre-computed MACD values from the data feed (compute_indicators).
    """

    def __init__(
        self,
        name: str = "macd_crossover",
        fast_period: int = 12,
        slow_period: int = 26,
        signal_period: int = 9,
        min_confidence: float = 0.6,
        position_size: float = 0.1,
    ) -> None:
        super().__init__(name=name)
        self.fast_period = fast_period
        self.slow_period = slow_period
        self.signal_period = signal_period
        self.min_confidence = min_confidence
        self.position_size = position_size
        self._prev_macd: float | None = None
        self._prev_signal: float | None = None

    def on_bar(self, candle: Candle) -> StrategySignal | None:
        macd_line = getattr(candle, "macd_line", None)
        macd_signal = getattr(candle, "macd_signal", None)

        if macd_line is None or macd_signal is None:
            return None

        if self._prev_macd is None or self._prev_signal is None:
            self._prev_macd = macd_line
            self._prev_signal = macd_signal
            return None

        # Crossover detection
        prev_hist = self._prev_macd - self._prev_signal
        curr_hist = macd_line - macd_signal

        if curr_hist > 0 and prev_hist <= 0:
            # Bullish crossover
            confidence = min(1.0, abs(curr_hist) / (abs(prev_hist) + 0.0001))
            signal = StrategySignal(
                action=SignalAction.BUY,
                symbol=candle.symbol,
                confidence=confidence,
                reason="MACD bullish crossover",
                timestamp=candle.timestamp,
                metadata={
                    "macd_line": macd_line,
                    "macd_signal": macd_signal,
                    "macd_histogram": curr_hist,
                },
            )
            self._prev_macd = macd_line
            self._prev_signal = macd_signal
            return signal

        if curr_hist < 0 and prev_hist >= 0:
            # Bearish crossover
            confidence = min(1.0, abs(curr_hist) / (abs(prev_hist) + 0.0001))
            signal = StrategySignal(
                action=SignalAction.SELL,
                symbol=candle.symbol,
                confidence=confidence,
                reason="MACD bearish crossover",
                timestamp=candle.timestamp,
                metadata={
                    "macd_line": macd_line,
                    "macd_signal": macd_signal,
                    "macd_histogram": curr_hist,
                },
            )
            self._prev_macd = macd_line
            self._prev_signal = macd_signal
            return signal

        self._prev_macd = macd_line
        self._prev_signal = macd_signal
        return None


# ─── Signal-Driven Strategy ─────────────────────────────────────────────────


class SignalDrivenStrategy(BaseStrategy):
    """Generic strategy that reacts to external signals.

    Useful for testing against pre-computed signals or simulated agents.
    """

    def __init__(
        self,
        name: str = "signal_driven",
        signal_provider: Any = None,
    ) -> None:
        super().__init__(name=name)
        self._signal_provider = signal_provider

    def on_bar(self, candle: Candle) -> StrategySignal | None:
        if self._signal_provider is None:
            return None

        # Call the signal provider's generate_signal method
        if hasattr(self._signal_provider, "generate_signal"):
            return self._signal_provider.generate_signal(candle)

        return None


# ─── Simulated Agents ───────────────────────────────────────────────────────


class SimulatedAgent(ABC):
    """Base class for simulated trading agents.

    Agents generate buy/sell signals during backtest.
    """

    def __init__(self, name: str = "simulated_agent", weight: float = 1.0) -> None:
        self.name = name
        self.weight = weight

    @abstractmethod
    def generate_signal(self, candle: Candle) -> StrategySignal:
        """Generate a trading signal for the given candle."""
        raise NotImplementedError


class RandomAgent(SimulatedAgent):
    """Agent that generates random signals.

    Useful for baseline testing and benchmark comparison.
    """

    def __init__(
        self,
        name: str = "random_agent",
        buy_probability: float = 0.5,
        avg_confidence: float = 0.5,
        confidence_std: float = 0.1,
    ) -> None:
        super().__init__(name=name)
        self.buy_probability = buy_probability
        self.avg_confidence = avg_confidence
        self.confidence_std = confidence_std

    def generate_signal(self, candle: Candle) -> StrategySignal:
        action = (
            SignalAction.BUY
            if np.random.random() < self.buy_probability
            else SignalAction.SELL
        )
        confidence = max(
            0.0, min(1.0, np.random.normal(self.avg_confidence, self.confidence_std))
        )
        return StrategySignal(
            action=action,
            symbol=candle.symbol,
            confidence=confidence,
            reason="random_signal",
            timestamp=candle.timestamp,
        )


class HeuristicAgent(SimulatedAgent):
    """Agent that uses simple technical heuristics.

    Uses RSI (overbought/oversold) and price trend.
    """

    def __init__(
        self,
        name: str = "heuristic_agent",
        rsi_overbought: float = 70,
        rsi_oversold: float = 30,
        trend_period: int = 20,
    ) -> None:
        super().__init__(name=name)
        self.rsi_overbought = rsi_overbought
        self.rsi_oversold = rsi_oversold
        self.trend_period = trend_period

    def generate_signal(self, candle: Candle) -> StrategySignal:
        rsi = getattr(candle, "rsi_14", None)

        if rsi is None or rsi == 0.0:
            return StrategySignal(
                action=SignalAction.NO_TRADE,
                symbol=candle.symbol,
                confidence=0.0,
                reason="no_rsi_data",
                timestamp=candle.timestamp,
            )

        if rsi <= self.rsi_oversold:
            return StrategySignal(
                action=SignalAction.BUY,
                symbol=candle.symbol,
                confidence=1.0 - (rsi / self.rsi_overbought),
                reason=f"RSI oversold ({rsi:.1f})",
                timestamp=candle.timestamp,
            )

        if rsi >= self.rsi_overbought:
            return StrategySignal(
                action=SignalAction.SELL,
                symbol=candle.symbol,
                confidence=(rsi - self.rsi_oversold) / self.rsi_overbought,
                reason=f"RSI overbought ({rsi:.1f})",
                timestamp=candle.timestamp,
            )

        return StrategySignal(
            action=SignalAction.HOLD,
            symbol=candle.symbol,
            confidence=0.0,
            reason="no_signal",
            timestamp=candle.timestamp,
        )
